"""
Match Companion — accessibility-first match understanding.

The World Cup is watched by billions who experience it very differently. This
module is built for the fans who are usually left out: people who cannot see the
screen well, cannot hear the commentary, or do not speak the broadcast language.

It turns a match's real StatsBomb events into a sequence of short, spoken-friendly
"beats" — a continuous audio description for blind / low-vision fans, doubling as
on-screen captions for deaf / hard-of-hearing fans, in any of 16 languages. The
narration is generated by IBM Granite from the actual event timeline, so it
describes what really happened, not a generic template.
"""

import os
import json
from dotenv import load_dotenv

load_dotenv('backend/.env')

from backend.granite import client, MODEL, lang_instruction
from backend.transparency import LIMITATIONS


def _gather(match_id: int, home_team: str, away_team: str):
    from backend.tactical_lens import get_key_moments
    from backend.emoti_pulse import get_emotion_arc
    moments = get_key_moments(match_id)
    arc = get_emotion_arc(match_id, home_team, away_team)
    final_score = arc.get('final_score', {}) if isinstance(arc, dict) else {}
    intensity = arc.get('intensity', '') if isinstance(arc, dict) else ''
    return moments, final_score, intensity


def generate_companion(match_id: int, home_team: str, away_team: str, lang: str = 'en') -> dict:
    moments, final_score, intensity = _gather(match_id, home_team, away_team)

    # Factual timeline (cap to keep the prompt focused on the headline beats)
    key = [m for m in moments if m.get('type') in ('Goal', 'Red Card', 'Yellow Card', 'Substitution')]
    key = key[:14]
    timeline = '\n'.join(
        f"{m['minute']}' {m['type']} - {m['player']} ({m['team']})" for m in key
    ) or 'No major events were recorded in the event data.'

    h = final_score.get(home_team, '?')
    a = final_score.get(away_team, '?')

    prompt = f"""You are creating an AUDIO DESCRIPTION of a finished football match for a fan who CANNOT see the screen. Your words are their only window into the game, so be clear, warm, and concrete.

MATCH: {home_team} vs {away_team}
FINAL SCORE: {home_team} {h} - {a} {away_team}
INTENSITY: {intensity}

REAL EVENT TIMELINE (from StatsBomb data — describe only these, invent nothing):
{timeline}

Produce a sequence of short spoken "beats" that walk the listener through the match in order. Rules:
- Start with one short opening beat naming the two teams and that the match has finished (do NOT reveal the final score in the opening beat — let it build).
- Then one beat for each event above, in chronological order, describing it in plain spoken language (e.g. "In the 23rd minute, {away_team} strike first — a goal from their forward.").
- End with one closing beat that states the final score and what made the match notable.
- Each beat is 1-2 short sentences, easy to follow when read aloud. No statistics jargon, no markdown, no emojis.

Respond with ONLY a JSON array, no prose before or after:
[{{"minute": <integer or null for opening/closing>, "text": "<the spoken beat>"}}]"""

    raw = client.chat.completions.create(
        model=MODEL,
        messages=[{'role': 'user', 'content': lang_instruction(lang) + prompt}],
        max_tokens=700,
    ).choices[0].message.content.strip()

    beats: list[dict] = []
    try:
        # Strip markdown code fences if present
        clean = raw.strip().removeprefix('```json').removeprefix('```').removesuffix('```').strip()
        start, end = clean.find('['), clean.rfind(']') + 1
        parsed = json.loads(clean[start:end])
        for b in parsed:
            if not isinstance(b, dict):
                continue
            text = str(b.get('text', '')).strip()
            # Skip beats where the model accidentally put raw JSON as the text
            if not text or text.startswith('[') or text.startswith('{'):
                continue
            beats.append({'minute': b.get('minute'), 'text': text})
    except Exception:
        # Fallback: split the raw narration into sentence-ish beats
        for chunk in [c.strip() for c in raw.replace('\n', ' ').split('. ') if c.strip()]:
            if not chunk.startswith('[') and not chunk.startswith('{'):
                beats.append({'minute': None, 'text': chunk.rstrip('.') + '.'})

    if not beats:
        beats = [{'minute': None, 'text': f'{home_team} played {away_team}. The match finished {h} to {a}.'}]

    return {
        'match': f'{home_team} vs {away_team}',
        'home_team': home_team,
        'away_team': away_team,
        'final_score': f'{h}–{a}',
        'intensity': intensity,
        'beats': beats,
        'limitations': LIMITATIONS['audio_match'],
    }
